# -*- mode: ruby -*-
# vi: set ft=ruby :

$dcos_box = ENV.fetch('DCOS_BOX', 'mesosphere/dcos-docker-sdk')
# TODO: when box isn't being upgraded regularly, switch from the raw URL to the (commented-out) cached URL:
#$dcos_box_url = ENV.fetch('DCOS_BOX_URL', 'https://downloads.mesosphere.com/dcos-docker-sdk/metadata.json')
$dcos_box_url = ENV.fetch('DCOS_BOX_URL', 'https://s3.amazonaws.com/downloads.mesosphere.io/dcos-docker-sdk/metadata.json')

$dcos_cpus = ENV.fetch('DCOS_CPUS', 2)
$dcos_mem = ENV.fetch('DCOS_MEM', 6144) # 6GB

# configure vbox host-only network
system('./vbox-network.sh')

Vagrant.configure(2) do |config|
  # configure vagrant-vbguest plugin
  if Vagrant.has_plugin?('vagrant-vbguest')
    config.vbguest.auto_update = true
  end

  config.vm.define 'dcos-docker-sdk' do |vm_cfg|
    vm_cfg.vm.box = $dcos_box
    vm_cfg.vm.box_url = $dcos_box_url

    vm_cfg.vm.hostname = 'dcos-docker-sdk'
    vm_cfg.vm.network :private_network, ip: '192.168.65.50'
    config.vm.synced_folder '.', '/vagrant', type: :virtualbox
    config.vm.synced_folder '../../', '/dcos-commons', type: :virtualbox

    vm_cfg.vm.provider :virtualbox do |v|
      v.name = vm_cfg.vm.hostname
      v.cpus = $dcos_cpus
      v.memory = $dcos_mem
      # configure guest to use host DNS resolver
      v.customize ['modifyvm', :id, '--natdnshostresolver1', 'on']
    end
  end
end
