repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.3.0
    hooks:
    - id: flake8
-   repo: local
    hooks:
    # - id: black
    #   name: black
    #   language: script
    #   entry: tools/ci/checks/run_black_checks.sh
    #   files: \.py$
    #   pass_filenames: true
    # - id: flake8
    #   name: flake8
    #   language: script
    #   entry: tools/ci/checks/run_flake8_checks.sh
    #   files: \.py$
    #   pass_filenames: true
    - id: pylint
      name: pylint
      entry: pylint
      args: [-E]
      language: system
      types: [python]
