repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      always_run: true
      args: [--check]
      language_version: python3
    - id: black
      always_run: true
      name: black-format
      language_version: python3
      stages: [manual]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.3.0
    hooks:
    - id: flake8
      always_run: true
-   repo: local
    hooks:
    - id: pylint
      name: pylint
      entry: pylint
      args: [-E, -j4]
      language: system
      types: [python]
      always_run: true
