language: java
sudo: required
dist: trusty
jdk:
  - openjdk8
before_install:
  - sudo add-apt-repository -y ppa:deadsnakes/ppa
  - sudo apt-get update -yq
  - sudo apt-get install -y python3.5
  - sudo apt-get install -y python3-setuptools python3-pip
  - sudo apt-get install -y awscli
  - eval "$(gimme 1.8.3)"
  - sudo ln -sf /usr/bin/python3.5 /usr/bin/python3
  - sudo pip install awscli
script:
  - ./gradlew check
  - if [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
      if [ -z "${PX_SDK_RELEASE_VERSION}" ]; then
        ./release.sh -r snapshot;
      else
        git remote remove origin;
        git remote add origin https://${GITHUB_TOKEN}@github.com/portworx/dcos-commons.git > /dev/null 2>&1;
        ./release.sh -r ${PX_SDK_RELEASE_VERSION};
      fi;
      frameworks/cassandra/build.sh aws;
      frameworks/elastic/build.sh aws;
      frameworks/hdfs/build.sh aws;
      frameworks/kafka/build.sh aws;
      frameworks/zookeeper/build.sh aws;
      frameworks/couchdb/build.sh aws;
      frameworks/portworx/build.sh aws;
    fi
notifications:
  email:
    on_success: always
    on_failure: always
