# This is the base image for mesosphere/dcos-commons, created in order to
# overcome issues such as DCOS-44265 which come about because neither the 18.04
# tag is immutable, nor the apt-get install command is repeatable.
#
# If you need a new version of this image (either because you require more
# recent versions of the base OS or one of the packages installed here, or
# because you modified this file), there are two ways to use it:
#
# 1) Slower but semi-automatic and public:
# - once the desired version of this file is merged to master, the builder
#   on Jenkins will build and push a new version of this image
# - at that point, renovatebot will make a PR to bump the sha in FROM line in
#   Dockerfile (of the main image)
#
# 2) Faster, for local testing:
# - make the required changes to this file, and/or run the following build
#   command with --no-cache 
# $ TAG=$(date +%Y%m%d)-local
# $ docker build -f Dockerfile.base -t mesosphere/dcos-commons-base:$TAG .
# - put the tag into the FROM line in Dockerfile (of the main image)
#   temporarily, rebuild that one, test, etc.
#
FROM ubuntu:18.10@sha256:7d657275047118bb77b052c4c0ae43e8a289ca2879ebfa78a703c93aa8fd686c

RUN apt-get update && \
    apt-get install -y python3-software-properties software-properties-common && \
    add-apt-repository -y ppa:openjdk-r/ppa && \
    apt-get update && \
    apt-get install -y \
    curl \
    git \
    jq \
    libcairo2-dev \
    libgirepository1.0-dev \
    libssl-dev \
    openjdk-8-jdk \
    pkg-config \
    python-pip \
    python3 \
    python3-cairo-dev \
    python3-dev \
    python3-pip \
    rsync \
    tox \
    software-properties-common \
    upx-ucl \
    wget \
    zip && \
    rm -rf /var/lib/apt/lists/* && \
    java -version

#Remove pycrypto-2.6.1 due to https://nvd.nist.gov/vuln/detail/CVE-2018-6594 
RUN apt-get remove -y python3-crypto
