{
 "title": "DC/OS 1.13 HDFS Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service_name",
    "label": "service_name",
    "query": "label_values({__name__=~\".*jvm_JvmMetrics_MemNonHeapUsedM\"}, service_name)"
   },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values({__name__=~\".*jvm_JvmMetrics_MemNonHeapUsedM\"}, instance)"
   },
   {
    "name": "task_name",
    "label": "task_name",
    "query": "label_values({__name__=~\".*jvm_JvmMetrics_MemNonHeapUsedM\", instance=~\"$instance\"}, task_name)"
   },
   { "name": "summary", "label": "summary", "query": "Summary" },
   { "name": "average", "label": "average", "query": "Average" },
   { "name": "time_range", "label": "time_range", "query": "60s, 300s, 3600s" }
  ]
 },
 "panels": [
  { "title": "JvmMetrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "MemNonHeapUsedM service ($service_name) instance ($instance)",
   "type": "graph",
   "description": "Current non-heap memory used in MB",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum({__name__=~\".*_jvm_JvmMetrics_MemNonHeapUsedM\",service_name=\"$service_name\",instance=~\"$instance\"})by(instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum({__name__=~\".*_jvm_JvmMetrics_MemNonHeapUsedM\",service_name=\"$service_name\",instance=~\"$instance\"})by(service_name)",
     "legendFormat": "$summary"
    }
   ]
  },
  {
   "title": "MemNonHeapMaxM service ($service_name) instance ($instance)",
   "type": "graph",
   "description": "Max non-heap memory size in MB",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum({__name__=~\".*_jvm_JvmMetrics_MemNonHeapMaxM\",service_name=\"$service_name\",instance=~\"$instance\"})by(instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum({__name__=~\".*_jvm_JvmMetrics_MemNonHeapMaxM\",service_name=\"$service_name\",instance=~\"$instance\"})by(service_name)",
     "legendFormat": "$summary"
    }
   ]
  },
  {
   "title": "MemHeapUsedM service ($service_name) instance ($instance)",
   "type": "graph",
   "description": "Current heap memory used in MB",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum({__name__=~\".*_jvm_JvmMetrics_MemHeapUsedM\",service_name=\"$service_name\",instance=~\"$instance\"})by(instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum({__name__=~\".*_jvm_JvmMetrics_MemHeapUsedM\",service_name=\"$service_name\",instance=~\"$instance\"})by(service_name)",
     "legendFormat": "$summary"
    }
   ]
  },
  {
   "title": "MemHeapMaxM service ($service_name) instance ($instance)",
   "type": "graph",
   "description": "Max heap memory size in MB",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum({__name__=~\".*_jvm_JvmMetrics_MemHeapMaxM\",service_name=\"$service_name\",instance=~\"$instance\"})by(instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum({__name__=~\".*_jvm_JvmMetrics_MemHeapMaxM\",service_name=\"$service_name\",instance=~\"$instance\"})by(service_name)",
     "legendFormat": "$summary"
    }
   ]
  },
  {
   "title": "ThreadsNew service ($service_name) instance ($instance)",
   "type": "graph",
   "description": "Current number of NEW threads",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum({__name__=~\".*_jvm_JvmMetrics_ThreadsNew\",service_name=\"$service_name\",instance=~\"$instance\"})by(instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum({__name__=~\".*_jvm_JvmMetrics_ThreadsNew\",service_name=\"$service_name\",instance=~\"$instance\"})by(service_name)",
     "legendFormat": "$summary"
    }
   ]
  },
  {
   "title": "ThreadsRunnable service ($service_name) instance ($instance)",
   "type": "graph",
   "description": "Current number of RUNNABLE threads",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum({__name__=~\".*_jvm_JvmMetrics_ThreadsRunnable\",service_name=\"$service_name\",instance=~\"$instance\"})by(instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum({__name__=~\".*_jvm_JvmMetrics_ThreadsRunnable\",service_name=\"$service_name\",instance=~\"$instance\"})by(service_name)",
     "legendFormat": "$summary"
    }
   ]
  },
  {
   "title": "RPC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "ReceivedBytes service ($service_name) instance ($instance)",
     "type": "graph",
     "description": "Total number of received bytes",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\".*_rpc_rpc_ReceivedBytes\",service_name=\"$service_name\",instance=~\"$instance\"})by(instance)",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "sum({__name__=~\".*_rpc_rpc_ReceivedBytes\",service_name=\"$service_name\",instance=~\"$instance\"})by(service_name)",
       "legendFormat": "$summary"
      }
     ]
    },
    {
     "title": "SentBytes service ($service_name) instance ($instance)",
     "type": "graph",
     "description": "Total number of sent bytes",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\".*_rpc_rpc_ReceivedBytes\",service_name=\"$service_name\",instance=~\"$instance\"})by(instance)",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "sum({__name__=~\".*_rpc_rpc_ReceivedBytes\",service_name=\"$service_name\",instance=~\"$instance\"})by(service_name)",
       "legendFormat": "$summary"
      }
     ]
    },
    {
     "title": "RpcQueueTimeNumOps service ($service_name) instance ($instance)",
     "type": "graph",
     "description": "Total number of RPC calls",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\".*_rpc_rpc_RpcQueueTimeNumOps\",service_name=\"$service_name\",instance=~\"$instance\"})by(instance)",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "sum({__name__=~\".*_rpc_rpc_RpcQueueTimeNumOps\",service_name=\"$service_name\",instance=~\"$instance\"})by(service_name)",
       "legendFormat": "$summary"
      }
     ]
    },
    {
     "title": "RpcQueueTimeAvgTime service ($service_name) instance ($instance)",
     "type": "graph",
     "description": "Average queue time in milliseconds",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "avg({__name__=~\".*_rpc_rpc_RpcQueueTimeAvgTime\",service_name=\"$service_name\",instance=~\"$instance\"})by(instance)",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "avg({__name__=~\".*_rpc_rpc_RpcQueueTimeAvgTime\",service_name=\"$service_name\",instance=~\"$instance\"})by(service_name)",
       "legendFormat": "$average"
      }
     ]
    },
    {
     "title": "RpcProcessingTimeNumOps service ($service_name) instance ($instance)",
     "type": "graph",
     "description": "Total number of RPC calls (same to RpcQueueTimeNumOps)",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\".*_rpc_rpc_RpcProcessingTimeNumOps\",service_name=\"$service_name\",instance=~\"$instance\"})by(instance)",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "sum({__name__=~\".*_rpc_rpc_RpcProcessingTimeNumOps\",service_name=\"$service_name\",instance=~\"$instance\"})by(service_name)",
       "legendFormat": "$summary"
      }
     ]
    },
    {
     "title": "RpcProcessingAvgTime service ($service_name) instance ($instance)",
     "type": "graph",
     "description": "Average Processing time in milliseconds",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "avg({__name__=~\".*_rpc_rpc_RpcProcessingTimeAvgTime\",service_name=\"$service_name\",instance=~\"$instance\"})by(instance)",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "avg({__name__=~\".*_rpc_rpc_RpcProcessingTimeAvgTime\",service_name=\"$service_name\",instance=~\"$instance\"})by(service_name)",
       "legendFormat": "$average"
      }
     ]
    },
    {
     "title": "RpcAuthenticationFailures service ($service_name) instance ($instance)",
     "type": "graph",
     "description": "Total number of authentication failures",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\".*_rpc_rpc_RpcAuthenticationFailures\",service_name=\"$service_name\",instance=~\"$instance\"})by(instance)",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "sum({__name__=~\".*_rpc_rpc_RpcAuthenticationFailures\",service_name=\"$service_name\",instance=~\"$instance\"})by(service_name)",
       "legendFormat": "$summary"
      }
     ]
    },
    {
     "title": "RpcAuthenticationSuccesses service ($service_name) instance ($instance)",
     "type": "graph",
     "description": "Total number of authentication successes",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\".*_rpc_rpc_RpcAuthenticationSuccesses\",service_name=\"$service_name\",instance=~\"$instance\"})by(instance)",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "sum({__name__=~\".*_rpc_rpc_RpcAuthenticationSuccesses\",service_name=\"$service_name\",instance=~\"$instance\"})by(service_name)",
       "legendFormat": "$summary"
      }
     ]
    },
    {
     "title": "RpcAuthorizationFailures service ($service_name) instance ($instance)",
     "type": "graph",
     "description": "Total number of authorization failures",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\".*_rpc_rpc_RpcAuthorizationFailures\",service_name=\"$service_name\",instance=~\"$instance\"})by(instance)",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "sum({__name__=~\".*_rpc_rpc_RpcAuthorizationFailures\",service_name=\"$service_name\",instance=~\"$instance\"})by(service_name)",
       "legendFormat": "$summary"
      }
     ]
    },
    {
     "title": "RpcAuthorizationSuccesses service ($service_name) instance (instance)",
     "type": "graph",
     "description": "Total number of authorization successes",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\".*_rpc_rpc_RpcAuthorizationSuccesses\",service_name=\"$service_name\",instance=~\"$instance\"})by(instance)",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "sum({__name__=~\".*_rpc_rpc_RpcAuthorizationSuccesses\",service_name=\"$service_name\",instance=~\"$instance\"})by(service_name)",
       "legendFormat": "$summary"
      }
     ]
    },
    {
     "title": "NumOpenConnections service ($service_name) instance ($instance)",
     "type": "graph",
     "description": "Current number of open connections",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\".*_rpc_rpc_NumOpenConnections\",service_name=\"$service_name\",instance=~\"$instance\"})by(instance)",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "sum({__name__=~\".*_rpc_rpc_NumOpenConnections\",service_name=\"$service_name\",instance=~\"$instance\"})by(service_name)",
       "legendFormat": "$summary"
      }
     ]
    }
   ]
  },
  {
   "title": "RetryCache/NameNodeRetryCache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "CacheHit service ($service_name) instance ($instance) task ($task_name)",
     "type": "graph",
     "description": "Total number of RetryCache hit",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\".*_CacheHit\",service_name=\"$service_name\",instance=~\"$instance\",task_name=~\"$task_name\"})by(instance,task_name)",
       "legendFormat": "{{instance}} / {{task_name}}"
      },
      {
       "expr": "sum({__name__=~\".*_CacheHit\",service_name=\"$service_name\",instance=~\"$instance\",task_name=~\"$task_name\"})by(service_name)",
       "legendFormat": "$summary"
      }
     ]
    },
    {
     "title": "CacheCleared service ($service_name) instance ($instance) task ($task_name)",
     "type": "graph",
     "description": "Total number of RetryCache cleared",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\".*_CacheCleared\",service_name=\"$service_name\",instance=~\"$instance\",task_name=~\"$task_name\"})by(instance,task_name)",
       "legendFormat": "{{instance}} / {{task_name}}"
      },
      {
       "expr": "sum({__name__=~\".*_CacheCleared\",service_name=\"$service_name\",instance=~\"$instance\",task_name=~\"$task_name\"})by(service_name)",
       "legendFormat": "$summary"
      }
     ]
    },
    {
     "title": "CacheUpdated service ($service_name) instance ($instance) task ($task_name)",
     "type": "graph",
     "description": "Total number of RetryCache updated",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\".*_CacheUpdated\",service_name=\"$service_name\",instance=~\"$instance\",task_name=~\"$task_name\"})by(instance,task_name)",
       "legendFormat": "{{instance}} / {{task_name}}"
      },
      {
       "expr": "sum({__name__=~\".*_CacheUpdated\",service_name=\"$service_name\",instance=~\"$instance\",task_name=~\"$task_name\"})by(service_name)",
       "legendFormat": "$summary"
      }
     ]
    }
   ]
  },
  {
   "title": "NameNode",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "CacheHit service ($service_name) instance ($instance) task ($task_name)",
     "type": "graph",
     "description": "Each metrics record contains tags such as ProcessName, SessionId, and Hostname as additional information along with metrics.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\".*_Syncs[[time_range]]NumOps\",service_name=\"$service_name\",instance=~\"$instance\",task_name=~\"$task_name\"})by(instance,task_name)",
       "legendFormat": "{{instance}} / {{task_name}}"
      },
      {
       "expr": "sum({__name__=~\".*_Syncs[[time_range]]NumOps\",service_name=\"$service_name\",instance=~\"$instance\",task_name=~\"$task_name\"})by(service_name)",
       "legendFormat": "$summary"
      }
     ]
    }
   ]
  },
  {
   "title": "JournalNode",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Syncs([[time_range]])NumOps instance ($instance) task ($task_name)",
     "type": "graph",
     "description": "Number of sync operations",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\".*_Syncs[[time_range]]NumOps\",service_name=\"$service_name\",instance=~\"$instance\",task_name=~\"$task_name\"})by(instance,task_name)",
       "legendFormat": "{{instance}} / {{task_name}}"
      },
      {
       "expr": "sum({__name__=~\".*_Syncs[[time_range]]NumOps\",service_name=\"$service_name\",instance=~\"$instance\",task_name=~\"$task_name\"})by(service_name)",
       "legendFormat": "$summary"
      }
     ]
    },
    {
     "title": "BatchesWritten instance ($instance) task ($task_name)",
     "type": "graph",
     "description": "Total number of batches written since startup",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\".*_BatchesWritten\",service_name=\"$service_name\",instance=~\"$instance\",task_name=~\"$task_name\"})by(instance,task_name)",
       "legendFormat": "{{instance}} / {{task_name}}"
      },
      {
       "expr": "sum({__name__=~\".*_BatchesWritten\",service_name=\"$service_name\",instance=~\"$instance\",task_name=~\"$task_name\"})by(service_name)",
       "legendFormat": "$summary"
      }
     ]
    },
    {
     "title": "TxnsWritten instance ($instance) task ($task_name)",
     "type": "graph",
     "description": "Total number of transactions written since startup",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\".*_TxnsWritten\",service_name=\"$service_name\",instance=~\"$instance\",task_name=~\"$task_name\"})by(instance,task_name)",
       "legendFormat": "{{instance}} / {{task_name}}"
      },
      {
       "expr": "sum({__name__=~\".*_TxnsWritten\",service_name=\"$service_name\",instance=~\"$instance\",task_name=~\"$task_name\"})by(service_name)",
       "legendFormat": "$summary"
      }
     ]
    },
    {
     "title": "BytesWritten instance ($instance) task ($task_name)",
     "type": "graph",
     "description": "Total number of bytes written since startup",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\".*_BytesWritten\",service_name=\"$service_name\",instance=~\"$instance\",task_name=~\"$task_name\"})by(instance,task_name)",
       "legendFormat": "{{instance}} / {{task_name}}"
      },
      {
       "expr": "sum({__name__=~\".*_BytesWritten\",service_name=\"$service_name\",instance=~\"$instance\",task_name=~\"$task_name\"})by(service_name)",
       "legendFormat": "$summary"
      }
     ]
    }
   ]
  },
  {
   "title": "UgiMetrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "LoginSuccessNumOps instance ($instance) task ($task_name)",
     "type": "graph",
     "description": "Total number of successful kerberos logins",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\".*_ugi_UgiMetrics_LoginSuccessNumOps\",service_name=\"$service_name\",instance=~\"$instance\",task_name=~\"$task_name\"})by(instance,task_name)",
       "legendFormat": "{{instance}} / {{task_name}}"
      },
      {
       "expr": "sum({__name__=~\".*_ugi_UgiMetrics_LoginSuccessNumOps\",service_name=\"$service_name\",instance=~\"$instance\",task_name=~\"$task_name\"})by(service_name)",
       "legendFormat": "$summary"
      }
     ]
    },
    {
     "title": "LoginFailureNumOps instance ($instance) task ($task_name)",
     "type": "graph",
     "description": "Total number of failed kerberos logins",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\".*_ugi_UgiMetrics_LoginFailureNumOps\",service_name=\"$service_name\",instance=~\"$instance\",task_name=~\"$task_name\"})by(instance,task_name)",
       "legendFormat": "{{instance}} / {{task_name}}"
      },
      {
       "expr": "sum({__name__=~\".*_ugi_UgiMetrics_LoginFailureNumOps\",service_name=\"$service_name\",instance=~\"$instance\",task_name=~\"$task_name\"})by(service_name)",
       "legendFormat": "$summary"
      }
     ]
    }
   ]
  },
  {
   "title": "MetricsSystem",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "NumActiveSources instance ($instance) task ($task_name)",
     "type": "graph",
     "description": "Current number of active metrics sources",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\".*_metricssystem_MetricsSystem_NumActiveSources\",service_name=\"$service_name\",instance=~\"$instance\",task_name=~\"$task_name\"})by(instance,task_name)",
       "legendFormat": "{{instance}} / {{task_name}}"
      },
      {
       "expr": "sum({__name__=~\".*_metricssystem_MetricsSystem_NumActiveSources\",service_name=\"$service_name\",instance=~\"$instance\",task_name=~\"$task_name\"})by(service_name)",
       "legendFormat": "$summary"
      }
     ]
    },
    {
     "title": "NumAllSources instance ($instance) task ($task_name)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\".*_metricssystem_MetricsSystem_NumAllSources\",service_name=\"$service_name\",instance=~\"$instance\",task_name=~\"$task_name\"})by(instance,task_name)",
       "legendFormat": "{{instance}} / {{task_name}}"
      },
      {
       "expr": "sum({__name__=~\".*_metricssystem_MetricsSystem_NumAllSources\",service_name=\"$service_name\",instance=~\"$instance\",task_name=~\"$task_name\"})by(service_name)",
       "legendFormat": "$summary"
      }
     ]
    },
    {
     "title": "NumActiveSinks instance ($instance) task ($task_name)",
     "type": "graph",
     "description": "Current number of active sinks",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\".*_metricssystem_MetricsSystem_NumActiveSinks\",service_name=\"$service_name\",instance=~\"$instance\",task_name=~\"$task_name\"})by(instance,task_name)",
       "legendFormat": "{{instance}} / {{task_name}}"
      },
      {
       "expr": "sum({__name__=~\".*_metricssystem_MetricsSystem_NumActiveSinks\",service_name=\"$service_name\",instance=~\"$instance\",task_name=~\"$task_name\"})by(service_name)",
       "legendFormat": "$summary"
      }
     ]
    }
   ]
  }
 ]
}