---
swagger: "2.0"
info:
  version: "0.0.1"
  title: "DC/OS SDK API Reference"
basePath: "/v1"
tags:
- name: "tasks"
  description: "The tasks the service must perform"
- name: "plans"
  description: "The deployment plan for the tasks"
- name: "configurations"
  description: "The service's configuration"
schemes:
- "http"
paths:
  /plans:
    get:
      tags:
      - "plans"
      summary: "Returns list of all configured plans."
      description: "Returns list of all configured plans."
      parameters: []
      responses:
        200:
          description: "List of plans."
        404:
          description: "Plans not found."
  /plans/{planName}:
    get:
      tags:
      - "plans"
      summary: "Returns a full list of the Plan's contents (incl all Phases/Blocks)."
      description: "Returns a full list of the Plan's contents (incl all Phases/Blocks)."
      parameters:
      - name: "planName"
        in: "path"
        description: "The name of the plan."
        required: true
        type: "string"
      responses:
        200:
          description: "List of the plan's contents."
        404:
          description: "Plan not found."
  /plans/{planName}/continue:
    post:
      tags:
      - "plans"
      summary: "Continues the execution of the plan."
      description: "Continues the execution of the plan."
      parameters:
      - name: "planName"
        in: "path"
        description: "The name of the plan."
        required: true
        type: "string"
      responses:
        200:
          description: "Received cmd continue."
        404:
          description: "Plan not found."
  /plans/{planName}/forceComplete:
    post:
      tags:
      - "plans"
      summary: "Force complete your plan."
      description: "Force complete your plan."
      parameters:
      - name: "planName"
        in: "path"
        description: "The name of the plan."
        required: true
        type: "string"
      responses:
        200:
          description: "Received cmd forceComplete."
        404:
          description: "Plan not found."
  /plans/{planName}/interrupt:
    post:
      tags:
      - "plans"
      summary: "Interrupts the execution of the specified plan."
      description: "Interrupts the execution of the specified plan."
      parameters:
      - name: "planName"
        in: "path"
        description: "The name of the plan."
        required: true
        type: "string"
      responses:
        200:
          description: "Received cmd interrupt."
        404:
          description: "Plan not found."
  /plans/{planName}/restart:
    post:
      tags:
      - "plans"
      summary: "Restart your plan."
      description: "Restart your plan."
      parameters:
      - name: "planName"
        in: "path"
        description: "The name of the plan."
        required: true
        type: "string"
      responses:
        200:
          description: "Received cmd restart."
        404:
          description: "Plan not found."
  /tasks:
    get:
      tags:
      - "tasks"
      summary: "Produces a listing of the names of all stored tasks."
      description: "Produces a listing of the names of all stored tasks."
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "List of tasks"
        404:
          description: "Failed to fetch list of task names"
  /tasks/connection/{taskName}:
    get:
      tags:
      - "tasks"
      summary: "Returns connection information for the given task."
      description: "Returns connection information for the given task."
      produces:
      - "application/json"
      parameters:
      - name: "taskName"
        in: "path"
        description: "The name of the task."
        required: true
        type: "string"
      responses:
        200:
          description: "Connection information for the task."
        404:
          description: "Connection information not found."
  /tasks/info/{taskName}:
    get:
      tags:
      - "tasks"
      summary: "Returns information about the specified task."
      description: "Returns information about the specified task."
      produces:
      - "application/json"
      parameters:
      - name: "taskName"
        in: "path"
        description: "The name of the task."
        required: true
        type: "string"
      responses:
        200:
          description: "Information about the task."
        404:
          description: "Failed to fetch requested TaskInfo for task."
  /tasks/restart/{taskName}:
    post:
      tags:
      - "tasks"
      summary: "Restarts a task you specify."
      description: "Restarts a task you specify."
      parameters:
      - name: "taskName"
        in: "path"
        description: "The name of the task."
        required: true
        type: "string"
      responses:
        200:
          description: "Task restarted.."
        404:
          description: "User requested to kill non-existent task."
  /tasks/status/{taskName}:
    get:
      tags:
      - "tasks"
      summary: "Produces the TaskStatus for the provided task name."
      description: "Produces the TaskStatus for the provided task name."
      produces:
      - "application/json"
      parameters:
      - name: "taskName"
        in: "path"
        description: "The name of the task."
        required: true
        type: "string"
      responses:
        200:
          description: "Status of the task."
        404:
          description: "Failed to fetch requested TaskStatus for task."
  /configurations:
    get:
      tags:
      - "configurations"
      summary: "Produces an ID listing of all stored configurations."
      description: "Produces an ID listing of all stored configurations."
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "List of stored configurations."
        404:
          description: "Failed to fetch list of configuration ids."
  /configurations/{configurationId}:
    get:
      tags:
      - "configurations"
      summary: "Produces the content of the provided configuration ID."
      description: "Produces the content of the provided configuration ID."
      produces:
      - "application/json"
      parameters:
      - name: "configurationId"
        in: "path"
        description: "The ID of the configuration."
        required: true
        type: "string"
      responses:
        200:
          description: "The content of the configuration."
        404:
          description: "Failed to fetch requested configuration with id."
  /configurations/targetId:
    get:
      tags:
      - "configurations"
      summary: "Produces the ID of the current target configuration."
      description: "Produces the ID of the current target configuration."
      produces:
      - "application/json"
      responses:
        200:
          description: "The ID of the current target configuration."
        404:
          description: "Failed to fetch target configuration."
  /configurations/target:
    get:
      tags:
      - "configurations"
      summary: "Produces the content of the current target configuration."
      description: "Produces the content of the current target configuration."
      produces:
      - "application/json"
      responses:
        200:
          description: "The content of the current target configuration."
        404:
          description: "."