{
 "title": "Cassandra: Cluster Summary",
 "description": "Dashboard for Cassandra Package",
 "tags": [
  "cassandra",
  "data-services"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "service_name",
    "label": "Service name",
    "query": "label_values(org_apache_cassandra_metrics_client_connectednativeclients, service_name)"
   },
   {
    "name": "task_name",
    "label": "Node",
    "query": "label_values(org_apache_cassandra_metrics_client_connectednativeclients, task_name)"
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "metric_interval", "label": "Event rate", "query": "mean,m1,m5,m15" },
   { "name": "percentile", "label": "percentile", "query": "p50,p75,p95,p98,p999" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Connected Native Clients",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(org_apache_cassandra_metrics_client_connectednativeclients{task_name=~\"$task_name\", service_name=\"$service_name\"})",
     "legendFormat": "Clients Count"
    }
   ]
  },
  {
   "title": "clientrequest failures, Read",
   "type": "singlestat",
   "description": "Number of read failures encountered.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(org_apache_cassandra_metrics_clientrequest_failures_read_[[metric_interval]]_rate{task_name=~\"$task_name\", service_name=\"$service_name\"})"
    }
   ]
  },
  {
   "title": "Storage Exceptions",
   "type": "singlestat",
   "description": "Number of internal exceptions caught. Under normal exceptions this should be zero.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(org_apache_cassandra_metrics_storage_exceptions{task_name=~\"$task_name\", service_name=\"$service_name\"})"
    }
   ]
  },
  {
   "title": "Unavailable exceptions, Read",
   "type": "singlestat",
   "description": "Number of unavailable exceptions encountered.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(org_apache_cassandra_metrics_clientrequest_unavailables_read_[[metric_interval]]_rate{task_name=~\"$task_name\", service_name=\"$service_name\"})"
    }
   ]
  },
  {
   "title": "Unavail. exceptions, caswrite",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(org_apache_cassandra_metrics_clientrequest_unavailables_caswrite_[[metric_interval]]_rate{task_name=~\"$task_name\", service_name=\"$service_name\"})"
    }
   ]
  },
  {
   "title": "Unavail. exceptions, casread",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(org_apache_cassandra_metrics_clientrequest_unavailables_casread_[[metric_interval]]_rate{task_name=~\"$task_name\", service_name=\"$service_name\"})"
    }
   ]
  },
  {
   "title": "Client Request Write failures",
   "type": "singlestat",
   "description": "Number of write failures encountered.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(org_apache_cassandra_metrics_clientrequest_failures_write_[[metric_interval]]_rate{task_name=~\"$task_name\", service_name=\"$service_name\"})"
    }
   ]
  },
  {
   "title": "clientrequest failures, caswrite",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(org_apache_cassandra_metrics_clientrequest_failures_caswrite_[[metric_interval]]_rate{task_name=~\"$task_name\", service_name=\"$service_name\"})"
    }
   ]
  },
  {
   "title": "Unavailable exceptions, Write",
   "type": "singlestat",
   "description": "Number of unavailable exceptions encountered.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(org_apache_cassandra_metrics_clientrequest_unavailables_write_[[metric_interval]]_rate{task_name=~\"$task_name\", service_name=\"$service_name\"})"
    }
   ]
  },
  {
   "title": "clientrequest Timeouts, Read",
   "type": "singlestat",
   "description": "Number of timeouts encountered.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(org_apache_cassandra_metrics_clientrequest_timeouts_read_[[metric_interval]]_rate{task_name=~\"$task_name\", service_name=\"$service_name\"})"
    }
   ]
  },
  {
   "title": "CR Timeouts, caswrite",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(org_apache_cassandra_metrics_clientrequest_timeouts_caswrite_[[metric_interval]]_rate{task_name=~\"$task_name\", service_name=\"$service_name\"})"
    }
   ]
  },
  {
   "title": "CR Timeouts, casread",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(org_apache_cassandra_metrics_clientrequest_timeouts_casread_[[metric_interval]]_rate{task_name=~\"$task_name\", service_name=\"$service_name\"})"
    }
   ]
  },
  {
   "title": "clientrequest failures, casread",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(org_apache_cassandra_metrics_clientrequest_failures_casread_[[metric_interval]]_rate{task_name=~\"$task_name\", service_name=\"$service_name\"})"
    }
   ]
  },
  {
   "title": "clientrequest Timeouts, Write",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(org_apache_cassandra_metrics_clientrequest_timeouts_write_[[metric_interval]]_rate{task_name=~\"$task_name\",service_name=\"$service_name\"})"
    }
   ]
  },
  {
   "title": "Dropped Messages, Mutation (Write)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(org_apache_cassandra_metrics_droppedmessage_dropped_mutation_[[metric_interval]]_rate{task_name=~\"$task_name\", service_name=\"$service_name\"}) by (task_name)",
     "legendFormat": "Dropped messages, {{task_name}}"
    }
   ]
  },
  {
   "title": "Dropped Messages, Read",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(org_apache_cassandra_metrics_droppedmessage_dropped_read_[[metric_interval]]_rate{task_name=~\"$task_name\", service_name=\"$service_name\"}) by (task_name)",
     "legendFormat": "Dropped messages, {{task_name}}"
    }
   ]
  },
  {
   "title": "Keyspaces & Tables",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "SSTable Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(org_apache_cassandra_metrics_table_livesstablecount_all { task_name=~\"$task_name\", service_name=\"$service_name\"}) by (task_name)",
       "legendFormat": "LiveSSTableCount, node: {{task_name}}"
      }
     ]
    },
    {
     "title": "Memtable Data Size",
     "type": "graph",
     "description": "Total amount of live data stored in the memtable, excluding any data structure overhead.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(org_apache_cassandra_metrics_table_memtablelivedatasize_all{task_name=~\"$task_name\", service_name=\"$service_name\"}) by (task_name)",
       "legendFormat": "Memtable Live data size ({{task_name}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "clientrequest Reads / sec, $metric_interval",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(org_apache_cassandra_metrics_clientrequest_latency_read_[[metric_interval]]_rate{task_name=~\"$task_name\", service_name=\"$service_name\"}) by (task_name)",
       "legendFormat": "Reads / sec, {{task_name}}"
      }
     ]
    },
    {
     "title": "clientrequest Writes/ sec, $metric_interval",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 29 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(org_apache_cassandra_metrics_clientrequest_latency_write_[[metric_interval]]_rate{task_name=~\"$task_name\", service_name=\"$service_name\"}) by (task_name)",
       "legendFormat": "Writes / sec, {{task_name}}"
      }
     ]
    },
    {
     "title": "clientrequest Read Latency, $percentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 29 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "sum(org_apache_cassandra_metrics_clientrequest_latency_read_[[percentile]]{task_name=~\"$task_name\", service_name=\"$service_name\"}) by (task_name)",
       "legendFormat": "Read Latency, {{task_name}}"
      }
     ]
    },
    {
     "title": "All tables Writes / sec, $metric_interval",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(org_apache_cassandra_metrics_table_writelatency_all_[[metric_interval]]_rate{task_name=~\"$task_name\", service_name=\"$service_name\"}) by (task_name)",
       "legendFormat": "Writes / sec, {{task_name}}"
      }
     ]
    },
    {
     "title": "All tables Reads / sec, $metric_interval",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 36 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(org_apache_cassandra_metrics_table_readlatency_all_[[metric_interval]]_rate{task_name=~\"$task_name\", service_name=\"$service_name\"}) by (task_name)",
       "legendFormat": "Read latency, {{task_name}}"
      }
     ]
    },
    {
     "title": "clientrequest Write Latency, $percentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 36 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "sum(org_apache_cassandra_metrics_clientrequest_latency_write_[[percentile]]{task_name=~\"$task_name\", service_name=\"$service_name\"}) by (task_name)",
       "legendFormat": "Write Latency, {{task_name}}"
      }
     ]
    },
    {
     "title": "All tables Write latency, ${percentile}",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "sum(org_apache_cassandra_metrics_table_writelatency_all_[[percentile]]{task_name=~\"$task_name\", service_name=\"$service_name\"}) by (task_name)",
       "legendFormat": "Write latency, {{task_name}}"
      }
     ]
    },
    {
     "title": "All tables Read latency, ${percentile}",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 43 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "sum(org_apache_cassandra_metrics_table_readlatency_all_[[percentile]]{task_name=~\"$task_name\", service_name=\"$service_name\"}) by (task_name)",
       "legendFormat": "Read latency, {{task_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Heap Memory usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_heap_max{task_name=~\"$task_name\", service_name=\"$service_name\"}) by (task_name)",
       "legendFormat": "Max, {{task_name}}"
      },
      {
       "expr": "sum(jvm_memory_heap_used{task_name=~\"$task_name\", service_name=\"$service_name\"}) by (task_name)",
       "legendFormat": "Used, {{task_name}}"
      }
     ]
    },
    {
     "title": "JVM Non-Heap Memory usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_non_heap_used{task_name=~\"$task_name\"}) by (task_name)",
       "legendFormat": "Used, {{task_name}}"
      },
      {
       "expr": "sum(jvm_memory_non_heap_committed{task_name=~\"$task_name\"}) by (task_name)",
       "legendFormat": "Commited, {{task_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Key cache requests rate, $metric_interval",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(org_apache_cassandra_metrics_cache_requests_keycache_[[metric_interval]]_rate{task_name=~\"$task_name\", service_name=\"$service_name\"}) by (task_name)",
       "legendFormat": "Requests rate, {{task_name}}"
      }
     ]
    },
    {
     "title": "KeyCache hit rate, $task_name",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 24 },
     "repeat": "task_name",
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(org_apache_cassandra_metrics_cache_hitrate_keycache{task_name=\"$task_name\", service_name=\"$service_name\"}) by (task_name)"
      }
     ]
    },
    {
     "title": "KeyCache hit rate, $task_name",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 27 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(org_apache_cassandra_metrics_cache_hitrate_keycache{task_name=\"$task_name\", service_name=\"$service_name\"}) by (task_name)"
      }
     ]
    },
    {
     "title": "KeyCache hit rate, $task_name",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 30 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(org_apache_cassandra_metrics_cache_hitrate_keycache{task_name=\"$task_name\", service_name=\"$service_name\"}) by (task_name)"
      }
     ]
    },
    {
     "title": "KeyCache hit rate, $task_name",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 33 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(org_apache_cassandra_metrics_cache_hitrate_keycache{task_name=\"$task_name\", service_name=\"$service_name\"}) by (task_name)"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Hints, $interval",
     "type": "graph",
     "description": "Number of hint messages written to this node since [re]start. Includes one entry for each host to be hinted per hint.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(org_apache_cassandra_metrics_storage_totalhints{task_name=~\"$task_name\", service_name=\"$service_name\"}[$interval])) by (task_name)",
       "legendFormat": "Total Hints, {{task_name}}"
      }
     ]
    },
    {
     "title": "Total Hints In Progress. $interval",
     "type": "graph",
     "description": "Number of hints attemping to be sent currently.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(org_apache_cassandra_metrics_storage_totalhintsinprogress{task_name=~\"$task_name\", service_name=\"$service_name\"}[$interval])) by (task_name)",
       "legendFormat": "Total Hints in progress, {{task_name}}"
      }
     ]
    },
    {
     "title": "Storage Load",
     "type": "graph",
     "description": "Size, in bytes, of the on disk data size this node manages.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(org_apache_cassandra_metrics_storage_load{task_name=~\"$task_name\", service_name=\"$service_name\"}) by (task_name)",
       "legendFormat": "Storage load, {{task_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Compaction",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pending Tasks",
     "type": "graph",
     "description": "Estimated number of compactions remaining to perform",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(org_apache_cassandra_metrics_compaction_pendingtasks{task_name=~\"$task_name\", service_name=\"$service_name\"}) by (task_name)",
       "legendFormat": "Task count, {{task_name}}"
      }
     ]
    },
    {
     "title": "Bytes compacted, $interval",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(org_apache_cassandra_metrics_compaction_bytescompacted{task_name=~\"$task_name\", service_name=~\"$service_name\"}[$interval])) by (task_name)",
       "legendFormat": "Bytes compacted on {{task_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "ParNew GC count, $interval",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(jvm_gc_parnew_count{task_name=~\"$task_name\", service_name=\"$service_name\"}[$interval])) by (task_name)",
       "legendFormat": "GC Count, {{task_name}}"
      }
     ]
    },
    {
     "title": "ConcurrentMarkSweep GC count, $interval",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(jvm_gc_concurrentmarksweep_count{task_name=~\"$task_name\", service_name=\"$service_name\"}[$interval])) by (task_name)",
       "legendFormat": "GC Count, {{task_name}}"
      }
     ]
    },
    {
     "title": "ParNew GC duration, $task_name, $interval",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 34 },
     "repeat": "task_name",
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(rate(jvm_gc_parnew_time{task_name=~\"$task_name\", service_name=\"$service_name\"}[$interval])) by (task_name) / \nsum(rate(jvm_gc_parnew_count{task_name=~\"$task_name\", service_name=\"$service_name\"}[$interval])) by (task_name)"
      }
     ]
    },
    {
     "title": "ParNew GC duration, $task_name, $interval",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 34 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(rate(jvm_gc_parnew_time{task_name=~\"$task_name\", service_name=\"$service_name\"}[$interval])) by (task_name) / \nsum(rate(jvm_gc_parnew_count{task_name=~\"$task_name\", service_name=\"$service_name\"}[$interval])) by (task_name)"
      }
     ]
    },
    {
     "title": "ParNew GC duration, $task_name, $interval",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 34 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(rate(jvm_gc_parnew_time{task_name=~\"$task_name\", service_name=\"$service_name\"}[$interval])) by (task_name) / \nsum(rate(jvm_gc_parnew_count{task_name=~\"$task_name\", service_name=\"$service_name\"}[$interval])) by (task_name)"
      }
     ]
    },
    {
     "title": "ParNew GC duration, $task_name, $interval",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 34 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(rate(jvm_gc_parnew_time{task_name=~\"$task_name\", service_name=\"$service_name\"}[$interval])) by (task_name) / \nsum(rate(jvm_gc_parnew_count{task_name=~\"$task_name\", service_name=\"$service_name\"}[$interval])) by (task_name)"
      }
     ]
    },
    {
     "title": "ConcMarkSweep GC duration, $task_name, $interval",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 37 },
     "repeat": "task_name",
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(rate(jvm_gc_concurrentmarksweep_time{task_name=\"$task_name\", service_name=\"$service_name\"}[$interval])) by (task_name) / \nsum(rate(jvm_gc_concurrentMarksweep_count{task_name=\"$task_name\", service_name=\"$service_name\"}[$interval])) by (task_name)"
      }
     ]
    },
    {
     "title": "ConcMarkSweep GC duration, $task_name, $interval",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 37 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(rate(jvm_gc_concurrentmarksweep_time{task_name=\"$task_name\", service_name=\"$service_name\"}[$interval])) by (task_name) / \nsum(rate(jvm_gc_concurrentMarksweep_count{task_name=\"$task_name\", service_name=\"$service_name\"}[$interval])) by (task_name)"
      }
     ]
    },
    {
     "title": "ConcMarkSweep GC duration, $task_name, $interval",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 37 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(rate(jvm_gc_concurrentmarksweep_time{task_name=\"$task_name\", service_name=\"$service_name\"}[$interval])) by (task_name) / \nsum(rate(jvm_gc_concurrentMarksweep_count{task_name=\"$task_name\", service_name=\"$service_name\"}[$interval])) by (task_name)"
      }
     ]
    },
    {
     "title": "ConcMarkSweep GC duration, $task_name, $interval",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 37 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(rate(jvm_gc_concurrentmarksweep_time{task_name=\"$task_name\", service_name=\"$service_name\"}[$interval])) by (task_name) / \nsum(rate(jvm_gc_concurrentMarksweep_count{task_name=\"$task_name\", service_name=\"$service_name\"}[$interval])) by (task_name)"
      }
     ]
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active tasks",
     "type": "table",
     "description": "Number of tasks being actively worked on by this pool.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "sum({__name__=~\"org_apache_cassandra_metrics_threadpools_activetasks_(.*)\", task_name=~\"$task_name\", service_name=\"$service_name\"}) by (__name__)",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Pending tasks",
     "type": "table",
     "description": "Number of queued tasks queued up on this pool.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
     "targets": [
      {
       "expr": "sum({__name__=~\"org_apache_cassandra_metrics_threadpools_pendingtasks_.*\", task_name=~\"$task_name\", service_name=\"$service_name\"}) by (__name__)",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Currently Blocked tasks",
     "type": "table",
     "description": "Number of tasks that are currently blocked due to queue saturation but on retry will become unblocked.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
     "targets": [
      {
       "expr": "sum({__name__=~\"org_apache_cassandra_metrics_threadpools_currentlyblockedtasks_.*\", task_name=~\"$task_name\", service_name=\"$service_name\"}) by (__name__)",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Total blocked tasks",
     "type": "table",
     "description": "Number of tasks that were blocked due to queue saturation.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
     "targets": [
      {
       "expr": "sum({__name__=~\"org_apache_cassandra_metrics_threadpools_totalblockedtasks_.*\", task_name=~\"$task_name\", service_name=\"$service_name\"}) by (__name__)",
       "legendFormat": "{{__name__}}"
      }
     ]
    }
   ]
  }
 ]
}