{
 "title": "/Cassandra DC/OS 1.13",
 "description": "Dashboard for Cassandra Package",
 "tags": [ "cassandra" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "service_name",
    "label": "Service name",
    "query": "label_values(org_apache_cassandra_metrics_Client_connectedNativeClients, service_name)"
   },
   {
    "name": "task_name",
    "label": "Node",
    "query": "label_values(org_apache_cassandra_metrics_Client_connectedNativeClients, task_name)"
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "metric_interval", "label": "Event rate", "query": "mean,m1,m5,m15" },
   { "name": "percentile", "label": "percentile", "query": "p50,p75,p95,p98,p999" },
   {
    "name": "keyspace",
    "label": "keyspace",
    "query": "{__name__=~\"org_apache_cassandra_metrics_keyspace_MemtableOnHeapDataSize_(.*)\", task_name=~\"$task_name\", service_name=\"$service_name\"}"
   },
   {
    "name": "table",
    "label": "table",
    "query": "{__name__=~\"org_apache_cassandra_metrics_Table_LiveSSTableCount_[[keyspace]]_(.*)\", task_name=~\"$task_name\", service_name=\"$service_name\"}"
   }
  ]
 },
 "panels": [
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ClientRequest Failures, Write",
   "type": "singlestat",
   "description": "Number of write failures encountered.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(org_apache_cassandra_metrics_ClientRequest_Failures_Write_[[metric_interval]]_rate{task_name=~\"$task_name\", service_name=\"$service_name\"})"
    }
   ]
  },
  {
   "title": "ClientRequest Timeouts, Write",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(org_apache_cassandra_metrics_ClientRequest_Timeouts_Write_[[metric_interval]]_rate{task_name=~\"$task_name\",service_name=\"$service_name\"})"
    }
   ]
  },
  {
   "title": "Unavailable exceptions, Write",
   "type": "singlestat",
   "description": "Number of unavailable exceptions encountered.",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(org_apache_cassandra_metrics_ClientRequest_Unavailables_Write_[[metric_interval]]_rate{task_name=~\"$task_name\", service_name=\"$service_name\"})"
    }
   ]
  },
  {
   "title": "ClientRequest Failures, CASWrite",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(org_apache_cassandra_metrics_ClientRequest_Failures_CASWrite_[[metric_interval]]_rate{task_name=~\"$task_name\", service_name=\"$service_name\"})"
    }
   ]
  },
  {
   "title": "CR Timeouts, CASWrite",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(org_apache_cassandra_metrics_ClientRequest_Timeouts_CASWrite_[[metric_interval]]_rate{task_name=~\"$task_name\", service_name=\"$service_name\"})"
    }
   ]
  },
  {
   "title": "Unavail. exceptions, CASRead",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(org_apache_cassandra_metrics_ClientRequest_Unavailables_CASRead_[[metric_interval]]_rate{task_name=~\"$task_name\", service_name=\"$service_name\"})"
    }
   ]
  },
  {
   "title": "Storage Exceptions",
   "type": "singlestat",
   "description": "Number of internal exceptions caught. Under normal exceptions this should be zero.",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(org_apache_cassandra_metrics_Storage_Exceptions{task_name=~\"$task_name\", service_name=\"$service_name\"})"
    }
   ]
  },
  {
   "title": "ClientRequest Failures, Read",
   "type": "singlestat",
   "description": "Number of read failures encountered.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(org_apache_cassandra_metrics_ClientRequest_Failures_Read_[[metric_interval]]_rate{task_name=~\"$task_name\", service_name=\"$service_name\"})"
    }
   ]
  },
  {
   "title": "ClientRequest Timeouts, Read",
   "type": "singlestat",
   "description": "Number of timeouts encountered.",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(org_apache_cassandra_metrics_ClientRequest_Timeouts_Read_[[metric_interval]]_rate{task_name=~\"$task_name\", service_name=\"$service_name\"})"
    }
   ]
  },
  {
   "title": "Unavailable exceptions, Read",
   "type": "singlestat",
   "description": "Number of unavailable exceptions encountered.",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(org_apache_cassandra_metrics_ClientRequest_Unavailables_Read_[[metric_interval]]_rate{task_name=~\"$task_name\", service_name=\"$service_name\"})"
    }
   ]
  },
  {
   "title": "ClientRequest Failures, CASRead",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(org_apache_cassandra_metrics_ClientRequest_Failures_CASRead_[[metric_interval]]_rate{task_name=~\"$task_name\", service_name=\"$service_name\"})"
    }
   ]
  },
  {
   "title": "CR Timeouts, CASRead",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(org_apache_cassandra_metrics_ClientRequest_Timeouts_CASRead_[[metric_interval]]_rate{task_name=~\"$task_name\", service_name=\"$service_name\"})"
    }
   ]
  },
  {
   "title": "Unavail. exceptions, CASWrite",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(org_apache_cassandra_metrics_ClientRequest_Unavailables_CASWrite_[[metric_interval]]_rate{task_name=~\"$task_name\", service_name=\"$service_name\"})"
    }
   ]
  },
  {
   "title": "Connected Native Clients",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(org_apache_cassandra_metrics_Client_connectedNativeClients{task_name=~\"$task_name\", service_name=\"$service_name\"})",
     "legendFormat": "Clients Count"
    }
   ]
  },
  {
   "title": "Dropped Messages, Mutation (Write)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(org_apache_cassandra_metrics_DroppedMessage_Dropped_MUTATION_[[metric_interval]]_rate{task_name=~\"$task_name\", service_name=\"$service_name\"}) by (task_name)",
     "legendFormat": "Dropped messages, {{task_name}}"
    }
   ]
  },
  {
   "title": "Dropped Messages, Read",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(org_apache_cassandra_metrics_DroppedMessage_Dropped_READ_[[metric_interval]]_rate{task_name=~\"$task_name\", service_name=\"$service_name\"}) by (task_name)",
     "legendFormat": "Dropped messages, {{task_name}}"
    }
   ]
  },
  { "title": "Keyspaces & Tables", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Live SSTable Count",
   "type": "graph",
   "description": "The number of live SSTables for this table.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(org_apache_cassandra_metrics_Table_LiveSSTableCount_[[keyspace]]_[[table]]{task_name=~\"$task_name\", service_name=\"$service_name\"}) by (task_name)",
     "legendFormat": "Live SSTables count (node: {{task_name}}, keyspace: ${keyspace}, table: ${table})"
    }
   ]
  },
  {
   "title": "Memtable Live Data Size",
   "type": "graph",
   "description": "Total amount of live data stored in the memtable, excluding any data structure overhead.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(org_apache_cassandra_metrics_Table_MemtableLiveDataSize_[[keyspace]]_[[table]]{task_name=~\"$task_name\", service_name=\"$service_name\"}) by (task_name)",
     "legendFormat": "Table size (node: {{task_name}}, keyspace: ${keyspace}, table: ${table})"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "ClientRequest Reads / sec, $metric_interval",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(org_apache_cassandra_metrics_ClientRequest_Latency_Read_[[metric_interval]]_rate{task_name=~\"$task_name\", service_name=\"$service_name\"}) by (task_name)",
     "legendFormat": "Reads / sec, {{task_name}}"
    }
   ]
  },
  {
   "title": "ClientRequest Writes/ sec, $metric_interval",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(org_apache_cassandra_metrics_ClientRequest_Latency_Write_[[metric_interval]]_rate{task_name=~\"$task_name\", service_name=\"$service_name\"}) by (task_name)",
     "legendFormat": "Writes / sec, {{task_name}}"
    }
   ]
  },
  {
   "title": "ClientRequest Read Latency, $percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum(org_apache_cassandra_metrics_ClientRequest_Latency_Read_[[percentile]]{task_name=~\"$task_name\", service_name=\"$service_name\"}) by (task_name)",
     "legendFormat": "Read Latency, {{task_name}}"
    }
   ]
  },
  {
   "title": "ClientRequest Write Latency, $percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum(org_apache_cassandra_metrics_ClientRequest_Latency_Write_[[percentile]]{task_name=~\"$task_name\", service_name=\"$service_name\"}) by (task_name)",
     "legendFormat": "Write Latency, {{task_name}}"
    }
   ]
  },
  {
   "title": "All tables Writes / sec, $metric_interval",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(org_apache_cassandra_metrics_Table_WriteLatency_all_[[metric_interval]]_rate{task_name=~\"$task_name\", service_name=\"$service_name\"}) by (task_name)",
     "legendFormat": "Writes / sec, {{task_name}}"
    }
   ]
  },
  {
   "title": "All tables Reads / sec, $metric_interval",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(org_apache_cassandra_metrics_Table_ReadLatency_all_[[metric_interval]]_rate{task_name=~\"$task_name\", service_name=\"$service_name\"}) by (task_name)",
     "legendFormat": "Read latency, {{task_name}}"
    }
   ]
  },
  {
   "title": "All tables Write latency, ${percentile}",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum(org_apache_cassandra_metrics_Table_WriteLatency_all_[[percentile]]{task_name=~\"$task_name\", service_name=\"$service_name\"}) by (task_name)",
     "legendFormat": "Write latency, {{task_name}}"
    }
   ]
  },
  {
   "title": "All tables Read latency, ${percentile}",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum(org_apache_cassandra_metrics_Table_ReadLatency_all_[[percentile]]{task_name=~\"$task_name\", service_name=\"$service_name\"}) by (task_name)",
     "legendFormat": "Read latency, {{task_name}}"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "JVM Heap Memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_heap_max{task_name=~\"$task_name\", service_name=\"$service_name\"}) by (task_name)",
     "legendFormat": "Max, {{task_name}}"
    },
    {
     "expr": "sum(jvm_memory_heap_used{task_name=~\"$task_name\", service_name=\"$service_name\"}) by (task_name)",
     "legendFormat": "Used, {{task_name}}"
    }
   ]
  },
  {
   "title": "JVM Non-Heap Memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_non_heap_used{task_name=~\"$task_name\"}) by (task_name)",
     "legendFormat": "Used, {{task_name}}"
    },
    {
     "expr": "sum(jvm_memory_non_heap_committed{task_name=~\"$task_name\"}) by (task_name)",
     "legendFormat": "Commited, {{task_name}}"
    }
   ]
  },
  { "title": "Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "Key cache requests rate, $metric_interval",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(org_apache_cassandra_metrics_Cache_Requests_KeyCache_[[metric_interval]]_rate{task_name=~\"$task_name\", service_name=\"$service_name\"}) by (task_name)",
     "legendFormat": "Requests rate, {{task_name}}"
    }
   ]
  },
  {
   "title": "KeyCache hit rate, $task_name",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 74 },
   "repeat": "task_name",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(org_apache_cassandra_metrics_Cache_HitRate_KeyCache{task_name=\"$task_name\", service_name=\"$service_name\"}) by (task_name)"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "Total Hints, $interval",
   "type": "graph",
   "description": "Number of hint messages written to this node since [re]start. Includes one entry for each host to be hinted per hint.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(org_apache_cassandra_metrics_Storage_TotalHints{task_name=~\"$task_name\", service_name=\"$service_name\"}[$interval])) by (task_name)",
     "legendFormat": "Total Hints, {{task_name}}"
    }
   ]
  },
  {
   "title": "Total Hints In Progress. $interval",
   "type": "graph",
   "description": "Number of hints attemping to be sent currently.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(org_apache_cassandra_metrics_Storage_TotalHintsInProgress{task_name=~\"$task_name\", service_name=\"$service_name\"}[$interval])) by (task_name)",
     "legendFormat": "Total Hints in progress, {{task_name}}"
    }
   ]
  },
  {
   "title": "Storage Load",
   "type": "graph",
   "description": "Size, in bytes, of the on disk data size this node manages.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 84 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(org_apache_cassandra_metrics_Storage_Load{task_name=~\"$task_name\", service_name=\"$service_name\"}) by (task_name)",
     "legendFormat": "Storage load, {{task_name}}"
    }
   ]
  },
  { "title": "Compaction", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 } },
  {
   "title": "Pending Tasks",
   "type": "graph",
   "description": "Estimated number of compactions remaining to perform",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(org_apache_cassandra_metrics_Compaction_PendingTasks{task_name=~\"$task_name\", service_name=\"$service_name\"}) by (task_name)",
     "legendFormat": "Task count, {{task_name}}"
    }
   ]
  },
  {
   "title": "Bytes compacted, $interval",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 94 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(org_apache_cassandra_metrics_Compaction_BytesCompacted{task_name=~\"$task_name\", service_name=~\"$service_name\"}[$interval])) by (task_name)",
     "legendFormat": "Bytes compacted on {{task_name}}"
    }
   ]
  },
  { "title": "Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 } },
  {
   "title": "ParNew GC count, $interval",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_ParNew_count{task_name=~\"$task_name\", service_name=\"$service_name\"}[$interval])) by (task_name)",
     "legendFormat": "GC Count, {{task_name}}"
    }
   ]
  },
  {
   "title": "ConcurrentMarkSweep GC count, $interval",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 104 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_ConcurrentMarkSweep_count{task_name=~\"$task_name\", service_name=\"$service_name\"}[$interval])) by (task_name)",
     "legendFormat": "GC Count, {{task_name}}"
    }
   ]
  },
  {
   "title": "ParNew GC duration, $task_name, $interval",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 113 },
   "repeat": "task_name",
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_ParNew_time{task_name=~\"$task_name\", service_name=\"$service_name\"}[$interval])) by (task_name) / \nsum(rate(jvm_gc_ParNew_count{task_name=~\"$task_name\", service_name=\"$service_name\"}[$interval])) by (task_name)"
    }
   ]
  },
  {
   "title": "ConcMarkSweep GC duration, $task_name, $interval",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 116 },
   "repeat": "task_name",
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_ConcurrentMarkSweep_time{task_name=\"$task_name\", service_name=\"$service_name\"}[$interval])) by (task_name) / \nsum(rate(jvm_gc_ConcurrentMarkSweep_count{task_name=\"$task_name\", service_name=\"$service_name\"}[$interval])) by (task_name)"
    }
   ]
  },
  { "title": "Saturation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 119 } },
  {
   "title": "Active tasks",
   "type": "table",
   "description": "Number of tasks being actively worked on by this pool.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 120 },
   "targets": [
    {
     "expr": "sum({__name__=~\"org_apache_cassandra_metrics_ThreadPools_ActiveTasks_(.*)\", task_name=~\"$task_name\", service_name=\"$service_name\"}) by (__name__)",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Pending tasks",
   "type": "table",
   "description": "Number of queued tasks queued up on this pool.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 120 },
   "targets": [
    {
     "expr": "sum({__name__=~\"org_apache_cassandra_metrics_ThreadPools_PendingTasks_.*\", task_name=~\"$task_name\", service_name=\"$service_name\"}) by (__name__)",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Currently Blocked tasks",
   "type": "table",
   "description": "Number of tasks that are currently blocked due to queue saturation but on retry will become unblocked.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 129 },
   "targets": [
    {
     "expr": "sum({__name__=~\"org_apache_cassandra_metrics_ThreadPools_CurrentlyBlockedTasks_.*\", task_name=~\"$task_name\", service_name=\"$service_name\"}) by (__name__)",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Total blocked tasks",
   "type": "table",
   "description": "Number of tasks that were blocked due to queue saturation.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 129 },
   "targets": [
    {
     "expr": "sum({__name__=~\"org_apache_cassandra_metrics_ThreadPools_TotalBlockedTasks_.*\", task_name=~\"$task_name\", service_name=\"$service_name\"}) by (__name__)",
     "legendFormat": "{{__name__}}"
    }
   ]
  }
 ]
}