PACKAGE_NAME = 'kafka'
SERVICE_NAME = PACKAGE_NAME
FOLDERED_SERVICE_NAME = '/test/integration/' + SERVICE_NAME
FOLDERED_SERVICE_AUTOIP_HOST = FOLDERED_SERVICE_NAME.replace('/', '') + '.autoip.dcos.thisdcos.directory'
FOLDERED_SERVICE_VIP_HOST = FOLDERED_SERVICE_NAME.replace('/', '') + '.l4lb.thisdcos.directory'
DEFAULT_BROKER_COUNT = 3
DEFAULT_PARTITION_COUNT = 1
DEFAULT_REPLICATION_FACTOR = 1
DEFAULT_PLAN_NAME = 'deploy'
DEFAULT_PHASE_NAME = 'Deployment'
DEFAULT_POD_TYPE = 'kafka'
DEFAULT_TASK_NAME = 'broker'

