package org.apache.mesos.file;

import org.apache.mesos.stream.StreamUtil;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Properties;

/**
 * Used for hdfs file system operations.
 */
public final class FileUtils {

  private static final Logger LOG = LoggerFactory.getLogger(FileUtils.class);

  private FileUtils() {
  }

  public static void createDir(File dataDir) {
    if (dataDir.exists()) {
      LOG.info("data dir exits:" + dataDir);
    } else if (!dataDir.mkdirs()) {
      LOG.error("unable to create dir: " + dataDir);
    }
  }

  /**
   * Delete a file or directory.
   */
  public static boolean deleteDirectory(File fileToDelete) {
    boolean deleted = false;

    try {
      if (fileToDelete.isDirectory()) {
        org.apache.commons.io.FileUtils.deleteDirectory(fileToDelete);
        deleted = true;
      } else {
        LOG.error("File is not a directory: " + fileToDelete);
      }
    } catch (IOException e) {
      LOG.error("Unable to delete directory: " + fileToDelete);
    }

    return deleted;
  }

  /**
   * Write the provided Properties to the provided File, with provided {@code comments} at the top of the file.
   * The file and/or parent directory will be created if they don't yet exist. Any existing file will be overwritten.
   *
   * @returns whether the properties were successfully written
   */
  public static boolean createPropertiesFile(File file, Properties properties) {
    FileOutputStream fos = null;
    try {
      fos = org.apache.commons.io.FileUtils.openOutputStream(file, false /* append */);
      properties.store(fos, "Autogenerated by the Mesos Framework, DO NOT EDIT");
    } catch (IOException e) {
      LOG.error(String.format("Unable to open properties file %s for writing", file.getAbsolutePath()), e);
      return false;
    } finally {
      StreamUtil.closeQuietly(fos);
    }
    return true;
  }
}
