package com.mesosphere.sdk.offer.evaluate;

import com.google.protobuf.TextFormat;
import com.mesosphere.sdk.offer.*;
import com.mesosphere.sdk.specification.VolumeSpec;
import org.apache.mesos.Protos;
import org.apache.mesos.Protos.Resource;
import org.apache.mesos.Protos.Resource.DiskInfo;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.*;

import static com.mesosphere.sdk.offer.evaluate.EvaluationOutcome.fail;
import static com.mesosphere.sdk.offer.evaluate.EvaluationOutcome.pass;

/**
 * This class evaluates an offer against a given {@link com.mesosphere.sdk.offer.OfferRequirement}, ensuring that it
 * contains an appropriately-sized volume, and creating any necessary instances of
 * {@link com.mesosphere.sdk.offer.ReserveOfferRecommendation} and
 * {@link com.mesosphere.sdk.offer.CreateOfferRecommendation} as necessary.
 */
public class VolumeEvaluationStage extends ResourceEvaluationStage {
    private static final Logger logger = LoggerFactory.getLogger(VolumeEvaluationStage.class);
    private final VolumeSpec volumeSpec;
    private final Optional<String> persistenceId;
    private Resource reservedResource;

    public VolumeEvaluationStage(
            VolumeSpec volumeSpec,
            String taskName,
            Optional<String> resourceId,
            Optional<String> persistenceId) {
        super(volumeSpec, resourceId, taskName);
        this.volumeSpec = volumeSpec;
        this.persistenceId = persistenceId;
    }

    private boolean createsVolume() {
        return !persistenceId.isPresent();
    }

    @Override
    public EvaluationOutcome evaluate(MesosResourcePool mesosResourcePool, PodInfoBuilder podInfoBuilder) {
        EvaluationOutcome evaluationOutcome = super.evaluate(mesosResourcePool, podInfoBuilder);
        if (!evaluationOutcome.isPassing()) {
            return evaluationOutcome;
        }

        List<OfferRecommendation> offerRecommendations = evaluationOutcome.getOfferRecommendations();
        Resource fulfilledResource = getFulfilledResource(reservedResource);

        if (createsVolume()) {
            logger.info("    Resource '{}' requires a CREATE operation", volumeSpec.getName());
            offerRecommendations.add(new CreateOfferRecommendation(mesosResourcePool.getOffer(), fulfilledResource));
        }

        logger.info("  Generated '{}' resource for task: [{}]",
                volumeSpec.getName(), TextFormat.shortDebugString(fulfilledResource));
        super.setProtos(podInfoBuilder, fulfilledResource);

        return pass(
                this,
                offerRecommendations,
                "Satisfied requirements for %s volume '%s'",
                volumeSpec.getType(),
                volumeSpec.getContainerPath());
    }

    protected Resource getFulfilledResource(Resource resource) {
        Resource.Builder builder = resource.toBuilder();
        String persistenceId = createsVolume() ?
                UUID.randomUUID().toString() :
                this.persistenceId.get();
        DiskInfo diskInfo = builder.getDisk().toBuilder()
                .setPersistence(DiskInfo.Persistence.newBuilder()
                        .setId(persistenceId)
                        .setPrincipal(volumeSpec.getPrincipal()))
                .setVolume(Protos.Volume.newBuilder()
                        .setMode(Protos.Volume.Mode.RW)
                        .setContainerPath(volumeSpec.getContainerPath()))
                .build();
        builder.setDisk(diskInfo);

        return builder.build();
    }

    @Override
    protected void setProtos(PodInfoBuilder podInfoBuilder, Resource resource) {
        // Save the resource generated by the base ResourceEvaluationStage
        this.reservedResource = resource;
    }

    private int getResourceIndex(List<Resource> resources, String resourceId) {
        if (resourceId == null) {
            return -1;
        }

        for (int i=0; i<resources.size(); i++) {
            Resource resource = resources.get(i);
            String localResourceId = ResourceUtils.getResourceId(resource);
            if (localResourceId == null) {
                continue;
            }

            if (localResourceId.equals(resourceId)) {
                return i;
            }
        }

        return -1;
    }
}
