{
 "title": "DC/OS 1.13 Elastic Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service_name",
    "label": "service_name",
    "query": "label_values({__name__=~\".*fs_total_available_in_bytes\"}, service_name)"
   },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values({__name__=~\".*fs_total_available_in_bytes\"}, instance)"
   },
   {
    "name": "task_name",
    "label": "task_name",
    "query": "label_values({__name__=~\".*fs_total_available_in_bytes\", instance=~\"$instance\"}, task_name)"
   },
   { "name": "time_interval", "label": "time_interval", "query": "1m,5m,15m" },
   { "name": "summary", "label": "summary", "query": "Summary" }
  ]
 },
 "panels": [
  {
   "title": "File system information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "FS total space: service ($service_name) instance ($instance) task ($task_name)",
     "type": "graph",
     "description": "Total size (in bytes) of all file stores",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\".*_fs_total_available_in_bytes\",service_name=\"$service_name\",instance=~\"$instance\", task_name=~\"$task_name\"})by(instance, task_name)",
       "legendFormat": "{{instance}} / {{task_name}}"
      },
      {
       "expr": "sum({__name__=~\".*_fs_total_available_in_bytes\",service_name=\"$service_name\",instance=~\"$instance\", task_name=~\"$task_name\"})by(service_name)",
       "legendFormat": "$summary"
      }
     ]
    },
    {
     "title": "FS total free space: service ($service_name) instance ($instance) task ($task_name)",
     "type": "graph",
     "description": "Total number of unallocated bytes in all file stores",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\".*_fs_total_free_in_bytes\",service_name=\"$service_name\",instance=~\"$instance\", task_name=~\"$task_name\"})by(instance, task_name)",
       "legendFormat": "{{instance}} / {{task_name}}"
      },
      {
       "expr": "sum({__name__=~\".*_fs_total_free_in_bytes\",service_name=\"$service_name\",instance=~\"$instance\", task_name=~\"$task_name\"})by(service_name)",
       "legendFormat": "$summary"
      }
     ]
    },
    {
     "title": "FS total available space: service ($service_name) instance ($instance) task ($task_name)",
     "type": "graph",
     "description": "Total number of bytes available to this Java virtual machine on all file stores. Depending on OS or process level restrictions, this might appear less than fs.total.free_in_bytes. This is the actual amount of free disk space the Elasticsearch node can utilise.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\".*_fs_total_available_in_bytes\",service_name=\"$service_name\",instance=~\"$instance\", task_name=~\"$task_name\"})by(instance, task_name)",
       "legendFormat": "{{instance}} / {{task_name}}"
      },
      {
       "expr": "sum({__name__=~\".*_fs_total_available_in_bytes\",service_name=\"$service_name\",instance=~\"$instance\", task_name=~\"$task_name\"})by(service_name)",
       "legendFormat": "$summary"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Http current open: service ($service_name) instance ($instance) task ($task_name)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\".*_http_current_open\",service_name=\"$service_name\",instance=~\"$instance\", task_name=~\"$task_name\"})by(instance, task_name)",
       "legendFormat": "{{instance}} / {{task_name}}"
      },
      {
       "expr": "sum({__name__=~\".*_http_current_open\",service_name=\"$service_name\",instance=~\"$instance\", task_name=~\"$task_name\"})by(service_name)",
       "legendFormat": "$summary"
      }
     ]
    },
    {
     "title": "Http total opened: service ($service_name) instance ($instance) task ($task_name)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\".*_http_total_opened\",service_name=\"$service_name\",instance=~\"$instance\", task_name=~\"$task_name\"})by(instance, task_name)",
       "legendFormat": "{{instance}} / {{task_name}}"
      },
      {
       "expr": "sum({__name__=~\".*_http_total_opened\",service_name=\"$service_name\",instance=~\"$instance\", task_name=~\"$task_name\"})by(service_name)",
       "legendFormat": "$summary"
      }
     ]
    }
   ]
  },
  {
   "title": "Operating system stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "OS CPU percent: service ($service_name) instance ($instance) task ($task_name)",
     "type": "graph",
     "description": "Recent CPU usage for the whole system, or -1 if not supported",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\".*_os_cpu_percent\",service_name=\"$service_name\",instance=~\"$instance\", task_name=~\"$task_name\"})by(instance, task_name)",
       "legendFormat": "{{instance}} / {{task_name}}"
      },
      {
       "expr": "sum({__name__=~\".*_os_cpu_percent\",service_name=\"$service_name\",instance=~\"$instance\", task_name=~\"$task_name\"})by(service_name)",
       "legendFormat": "$summary"
      }
     ]
    },
    {
     "title": "OS load average: interval ($time_interval) service ($service_name) instance ($instance) task ($task_name)",
     "type": "graph",
     "description": "($time_interval) load average on the system (field is not present if one-minute load average is not available)",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\".*os_load_average_[[time_interval]]\",service_name=\"$service_name\",instance=~\"$instance\", task_name=~\"$task_name\"})by(instance, task_name)",
       "legendFormat": "{{instance}} / {{task_name}}"
      },
      {
       "expr": "sum({__name__=~\".*os_load_average_[[time_interval]]\",service_name=\"$service_name\",instance=~\"$instance\", task_name=~\"$task_name\"})by(service_name)",
       "legendFormat": "$summary"
      }
     ]
    },
    {
     "title": "OS memory free: service ($service_name) instance ($instance) task ($task_name)",
     "type": "graph",
     "description": "Amount of free physical memory in bytes",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\".*_os_mem_free_in_bytes\",service_name=\"$service_name\",instance=~\"$instance\", task_name=~\"$task_name\"})by(instance, task_name)",
       "legendFormat": "{{instance}} / {{task_name}}"
      },
      {
       "expr": "sum({__name__=~\".*_os_mem_free_in_bytes\",service_name=\"$service_name\",instance=~\"$instance\", task_name=~\"$task_name\"})by(service_name)",
       "legendFormat": "$summary"
      }
     ]
    },
    {
     "title": "OS memory free percent: service ($service_name) instance ($instance) task ($task_name)",
     "type": "graph",
     "description": "Percentage of free memory",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\".*_os_mem_free_percent\",service_name=\"$service_name\",instance=~\"$instance\", task_name=~\"$task_name\"})by(instance, task_name)",
       "legendFormat": "{{instance}} / {{task_name}}"
      },
      {
       "expr": "sum({__name__=~\".*_os_mem_free_percent\",service_name=\"$service_name\",instance=~\"$instance\", task_name=~\"$task_name\"})by(service_name)",
       "legendFormat": "$summary"
      }
     ]
    },
    {
     "title": "OS memory used: service ($service_name) instance ($instance) task ($task_name)",
     "type": "graph",
     "description": "Amount of used physical memory in bytes",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\".*_os_mem_used_in_bytes\",service_name=\"$service_name\",instance=~\"$instance\", task_name=~\"$task_name\"})by(instance, task_name)",
       "legendFormat": "{{instance}} / {{task_name}}"
      },
      {
       "expr": "sum({__name__=~\".*_os_mem_used_in_bytes\",service_name=\"$service_name\",instance=~\"$instance\", task_name=~\"$task_name\"})by(service_name)",
       "legendFormat": "$summary"
      }
     ]
    },
    {
     "title": "OS memory used percent: service ($service_name) instance ($instance) task ($task_name)",
     "type": "graph",
     "description": "Percentage of used memory",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\".*_os_mem_used_percent\",service_name=\"$service_name\",instance=~\"$instance\", task_name=~\"$task_name\"})by(instance, task_name)",
       "legendFormat": "{{instance}} / {{task_name}}"
      },
      {
       "expr": "sum({__name__=~\".*_os_mem_used_percent\",service_name=\"$service_name\",instance=~\"$instance\", task_name=~\"$task_name\"})by(service_name)",
       "legendFormat": "$summary"
      }
     ]
    }
   ]
  },
  {
   "title": "Process statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process CPU percent: service ($service_name) instance ($instance) task ($task_name)",
     "type": "graph",
     "description": "CPU usage in percent, or -1 if not known at the time the stats are computed",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\".*_process_cpu_percent\",service_name=\"$service_name\",instance=~\"$instance\", task_name=~\"$task_name\"})by(instance, task_name)",
       "legendFormat": "{{instance}} / {{task_name}}"
      },
      {
       "expr": "sum({__name__=~\".*_process_cpu_percent\",service_name=\"$service_name\",instance=~\"$instance\", task_name=~\"$task_name\"})by(service_name)",
       "legendFormat": "$summary"
      }
     ]
    },
    {
     "title": "Process memory total virtual: service ($service_name) instance ($instance) task ($task_name)",
     "type": "graph",
     "description": "Size in bytes of virtual memory that is guaranteed to be available to the running process",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\".*_process_mem_total_virtual_in_bytes\",service_name=\"$service_name\",instance=~\"$instance\", task_name=~\"$task_name\"})by(instance, task_name)",
       "legendFormat": "{{instance}} / {{task_name}}"
      },
      {
       "expr": "sum({__name__=~\".*_process_mem_total_virtual_in_bytes\",service_name=\"$service_name\",instance=~\"$instance\", task_name=~\"$task_name\"})by(service_name)",
       "legendFormat": "$summary"
      }
     ]
    },
    {
     "title": "Process open file descriptors: service ($service_name) instance ($instance) task ($task_name)",
     "type": "graph",
     "description": "Number of opened file descriptors associated with the current process, or -1 if not supported",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\".*_process_open_file_descriptors\",service_name=\"$service_name\",instance=~\"$instance\", task_name=~\"$task_name\"})by(instance, task_name)",
       "legendFormat": "{{instance}} / {{task_name}}"
      },
      {
       "expr": "sum({__name__=~\".*_process_open_file_descriptors\",service_name=\"$service_name\",instance=~\"$instance\", task_name=~\"$task_name\"})by(service_name)",
       "legendFormat": "$summary"
      }
     ]
    }
   ]
  },
  {
   "title": "Transport statistics about sent and received bytes in cluster communication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transport rx count: service ($service_name) instance ($instance) task ($task_name)",
     "type": "graph",
     "description": "The total number of packets received in cluster communication.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\".*_transport_rx_count\",service_name=\"$service_name\",instance=~\"$instance\", task_name=~\"$task_name\"})by(instance, task_name)",
       "legendFormat": "{{instance}} / {{task_name}}"
      },
      {
       "expr": "sum({__name__=~\".*_transport_rx_count\",service_name=\"$service_name\",instance=~\"$instance\", task_name=~\"$task_name\"})by(service_name)",
       "legendFormat": "$summary"
      }
     ]
    },
    {
     "title": "Transport rx size in bytes: service ($service_name) instance ($instance) task ($task_name)",
     "type": "graph",
     "description": "The total size of data received in cluster communication.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\".*_transport_rx_size_in_bytes\",service_name=\"$service_name\",instance=~\"$instance\", task_name=~\"$task_name\"})by(instance, task_name)",
       "legendFormat": "{{instance}} / {{task_name}}"
      },
      {
       "expr": "sum({__name__=~\".*_transport_rx_size_in_bytes\",service_name=\"$service_name\",instance=~\"$instance\", task_name=~\"$task_name\"})by(service_name)",
       "legendFormat": "$summary"
      }
     ]
    },
    {
     "title": "Transport server open: service ($service_name) instance ($instance) task ($task_name)",
     "type": "graph",
     "description": "Indicate in the transport channel to send and receive data is open.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\".*_transport_server_open\",service_name=\"$service_name\",instance=~\"$instance\", task_name=~\"$task_name\"})by(instance, task_name)",
       "legendFormat": "{{instance}} / {{task_name}}"
      },
      {
       "expr": "sum({__name__=~\".*_transport_server_open\",service_name=\"$service_name\",instance=~\"$instance\", task_name=~\"$task_name\"})by(service_name)",
       "legendFormat": "$summary"
      }
     ]
    },
    {
     "title": "Transport tx count: service ($service_name) instance ($instance) task ($task_name)",
     "type": "graph",
     "description": "The total number of packets sent in cluster communication.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\".*_transport_tx_count\",service_name=\"$service_name\",instance=~\"$instance\", task_name=~\"$task_name\"})by(instance, task_name)",
       "legendFormat": "{{instance}} / {{task_name}}"
      },
      {
       "expr": "sum({__name__=~\".*_transport_tx_count\",service_name=\"$service_name\",instance=~\"$instance\", task_name=~\"$task_name\"})by(service_name)",
       "legendFormat": "$summary"
      }
     ]
    },
    {
     "title": "Transport tx size in bytes: service ($service_name) instance ($instance) task ($task_name)",
     "type": "graph",
     "description": "The total size of data sent in cluster communication.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\".*_transport_tx_size_in_bytes\",service_name=\"$service_name\",instance=~\"$instance\", task_name=~\"$task_name\"})by(instance, task_name)",
       "legendFormat": "{{instance}} / {{task_name}}"
      },
      {
       "expr": "sum({__name__=~\".*_transport_tx_size_in_bytes\",service_name=\"$service_name\",instance=~\"$instance\", task_name=~\"$task_name\"})by(service_name)",
       "legendFormat": "$summary"
      }
     ]
    }
   ]
  },
  {
   "title": "Thread pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Thread pool analyze active: service ($service_name) instance ($instance) task ($task_name)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\".*_thread_pool_analyze_active\",service_name=\"$service_name\",instance=~\"$instance\", task_name=~\"$task_name\"})by(instance, task_name)",
       "legendFormat": "{{instance}} / {{task_name}}"
      },
      {
       "expr": "sum({__name__=~\".*thread_pool_analyze_active\",service_name=\"$service_name\",instance=~\"$instance\", task_name=~\"$task_name\"})by(service_name)",
       "legendFormat": "$summary"
      }
     ]
    },
    {
     "title": "Thread pool analyze completed: service ($service_name) instance ($instance) task ($task_name)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\".*thread_pool_analyze_completed\",service_name=\"$service_name\",instance=~\"$instance\", task_name=~\"$task_name\"})by(instance, task_name)",
       "legendFormat": "{{instance}} / {{task_name}}"
      },
      {
       "expr": "sum({__name__=~\".*thread_pool_analyze_completed\",service_name=\"$service_name\",instance=~\"$instance\", task_name=~\"$task_name\"})by(service_name)",
       "legendFormat": "$summary"
      }
     ]
    },
    {
     "title": "Thread pool get active: service ($service_name) instance ($instance) task ($task_name)",
     "type": "graph",
     "description": "The number of active threads in the get pool",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\".*_thread_pool_get_active\",service_name=\"$service_name\",instance=~\"$instance\", task_name=~\"$task_name\"})by(instance, task_name)",
       "legendFormat": "{{instance}} / {{task_name}}"
      },
      {
       "expr": "sum({__name__=~\".*_thread_pool_get_active\",service_name=\"$service_name\",instance=~\"$instance\", task_name=~\"$task_name\"})by(service_name)",
       "legendFormat": "$summary"
      }
     ]
    },
    {
     "title": "Thread pool get completed: service ($service_name) instance ($instance) task ($task_name)",
     "type": "graph",
     "description": "The number of completed threads in the get pool",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\".*_thread_pool_get_completed\",service_name=\"$service_name\",instance=~\"$instance\", task_name=~\"$task_name\"})by(instance, task_name)",
       "legendFormat": "{{instance}} / {{task_name}}"
      },
      {
       "expr": "sum({__name__=~\".*_thread_pool_get_completed\",service_name=\"$service_name\",instance=~\"$instance\", task_name=~\"$task_name\"})by(service_name)",
       "legendFormat": "$summary"
      }
     ]
    }
   ]
  }
 ]
}