#!/usr/bin/env python3

import logging
import argparse
import subprocess
import os

logging.basicConfig(level="INFO")

LOGGER = logging.getLogger(__name__)


def copy_dist_file(filename: str, output_path: str):
    """Copy a distribution file to the specified output path"""
    source_file = os.path.join("/dcos-commons-dist", filename)

    LOGGER.info("Copying %s to %s", source_file, output_path)
    subprocess.check_output(["cp", source_file, output_path])


def distribute_test_utils(output_path: str):
    """Copies the required files into the target folders"""

    output_path = output_path.rstrip("/") + "/"

    files = ["test.sh", "TESTING.md", ]

    for f in files:
        copy_dist_file(f, output_path)


def parse_args():
    parser = argparse.ArgumentParser(description="Init DC/OS test environment")
    parser.add_argument('output_path', type=str,
                        help='The absolute path where the testing tools should be created')

    return parser.parse_args()


def main():
    args = parse_args()
    distribute_test_utils(args.output_path)


if __name__ == "__main__":
    main()
