package com.mesosphere.sdk.testing;

import java.util.Map;

import com.mesosphere.sdk.specification.ServiceSpec;
import com.mesosphere.sdk.specification.yaml.RawServiceSpec;

/**
 * An object which contains the generated results from rendering a Service via {@link ServiceTestBuilder}.
 */
public class ServiceTestResult {

    private final ServiceSpec serviceSpec;
    private final RawServiceSpec rawServiceSpec;
    private final Map<String, String> schedulerEnvironment;

    ServiceTestResult(
            ServiceSpec serviceSpec,
            RawServiceSpec rawServiceSpec,
            Map<String, String> schedulerEnvironment) {
        this.serviceSpec = serviceSpec;
        this.rawServiceSpec = rawServiceSpec;
        this.schedulerEnvironment = schedulerEnvironment;
    }

    /**
     * Returns the {@link ServiceSpec} (translated Service Specification) which was generated by the test.
     */
    public ServiceSpec getServiceSpec() {
        return serviceSpec;
    }

    /**
     * Returns the {@link RawServiceSpec} (object model of a {@code svc.yml}) which was generated by the test.
     */
    public RawServiceSpec getRawServiceSpec() {
        return rawServiceSpec;
    }

    /**
     * Returns the Scheduler environment which was generated by the test.
     */
    public Map<String, String> getSchedulerEnvironment() {
        return schedulerEnvironment;
    }
}
