{
 "title": "Scheduler Stats",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Launch Groups [1m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "launches/s" }
   ],
   "targets": [
    {
     "expr": "rate(operation_launch_group[1m])",
     "legendFormat": "{{dcos_service_name}}"
    }
   ]
  },
  {
   "title": "Launch Groups [1m] (stacked)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "launches/s" }
   ],
   "targets": [
    {
     "expr": "rate(operation_launch_group[1m])",
     "legendFormat": "{{dcos_service_name}}"
    }
   ]
  },
  {
   "title": "Offers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(rate(offers_received[1m]))" },
    {
     "expr": "sum(rate(offers_processed[1m]))"
    }
   ]
  },
  {
   "title": "Processed Offers [1m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "offers/s" }
   ],
   "targets": [
    { "expr": "rate(offers_processed[1m])", "legendFormat": "{{dcos_service_name}}" }
   ]
  },
  {
   "title": "Processed Offers [1m](stacked)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "offers/s" }
   ],
   "targets": [
    { "expr": "rate(offers_processed[1m])", "legendFormat": "{{dcos_service_name}}" }
   ]
  },
  {
   "title": "Suppresses [1m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "count(suppresses)", "legendFormat": "{{dcos_service_name}}" }
   ]
  },
  {
   "title": "Received offers [1m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "offers/s" }
   ],
   "targets": [
    { "expr": "rate(offers_received[1m])", "legendFormat": "{{dcos_service_name}}" }
   ]
  },
  {
   "title": "Received offers [1m](stacked)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "offers/s" }
   ],
   "targets": [
    { "expr": "rate(offers_received[1m])", "legendFormat": "{{dcos_service_name}}" }
   ]
  },
  {
   "title": "Revives [1m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(revives[1m])", "legendFormat": "{{dcos_service_name}}" }
   ]
  },
  {
   "title": "Short Declines [1m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(declines_short[1m])", "legendFormat": "{{dcos_service_name}}" }
   ]
  },
  {
   "title": "Long Declines [1m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(declines_long[1m])", "legendFormat": "{{dcos_service_name}}" }
   ]
  },
  {
   "title": "Revive Throttle",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(revives_throttles[1m])", "legendFormat": "{{dcos_service_name}}" }
   ]
  },
  {
   "title": "Short Declines [1m] (total)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(rate(declines_short[1m]))", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Long Declines [1m] (total)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(rate(declines_long[1m]))", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Offer Queue Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "com_mesosphere_sdk_framework_offerqueue_queue_size",
     "legendFormat": "{{dcos_service_name}}"
    }
   ]
  }
 ]
}